// Generated by gencpp from file sam_custom_messages/Object.msg
// DO NOT EDIT!


#ifndef SAM_CUSTOM_MESSAGES_MESSAGE_OBJECT_H
#define SAM_CUSTOM_MESSAGES_MESSAGE_OBJECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sam_custom_messages
{
template <class ContainerAllocator>
struct Object_
{
  typedef Object_<ContainerAllocator> Type;

  Object_()
    : id(0)
    , type(0)
    , info()  {
    }
  Object_(const ContainerAllocator& _alloc)
    : id(0)
    , type(0)
    , info(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _id_type;
  _id_type id;

   typedef int8_t _type_type;
  _type_type type;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _info_type;
  _info_type info;





  typedef boost::shared_ptr< ::sam_custom_messages::Object_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sam_custom_messages::Object_<ContainerAllocator> const> ConstPtr;

}; // struct Object_

typedef ::sam_custom_messages::Object_<std::allocator<void> > Object;

typedef boost::shared_ptr< ::sam_custom_messages::Object > ObjectPtr;
typedef boost::shared_ptr< ::sam_custom_messages::Object const> ObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sam_custom_messages::Object_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sam_custom_messages::Object_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sam_custom_messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['C:/Program Files/MATLAB/R2020b/sys/ros1/win64/ros1/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['C:/Program Files/MATLAB/R2020b/sys/ros1/win64/ros1/share/geometry_msgs/cmake/../msg'], 'sam_custom_messages': ['C:/Users/inter/Documents/NatNet_SDK_3.1/NatNetSDK/Industrial_SAM/matlab_msg_gen_ros1/win64/src/sam_custom_messages/msg'], 'std_msgs': ['C:/Program Files/MATLAB/R2020b/sys/ros1/win64/ros1/share/std_msgs/cmake/../msg', 'C:/Program Files/MATLAB/R2020b/sys/ros1/win64/ros1/share/std_msgs/cmake/../msg'], 'diagnostic_msgs': ['C:/Program Files/MATLAB/R2020b/sys/ros1/win64/ros1/share/diagnostic_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sam_custom_messages::Object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sam_custom_messages::Object_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sam_custom_messages::Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sam_custom_messages::Object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sam_custom_messages::Object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sam_custom_messages::Object_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sam_custom_messages::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc95ebc586991f7be21fb0175298a82c";
  }

  static const char* value(const ::sam_custom_messages::Object_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc95ebc586991f7bULL;
  static const uint64_t static_value2 = 0xe21fb0175298a82cULL;
};

template<class ContainerAllocator>
struct DataType< ::sam_custom_messages::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sam_custom_messages/Object";
  }

  static const char* value(const ::sam_custom_messages::Object_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sam_custom_messages::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message containg information on objects within environment\n"
"#\n"
"# Unique ID of object\n"
"int8 id\n"
"#\n"
"# Type of object ID\n"
"int8 type\n"
"#\n"
"# Additional information on object\n"
"string[] info\n"
;
  }

  static const char* value(const ::sam_custom_messages::Object_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sam_custom_messages::Object_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.type);
      stream.next(m.info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Object_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sam_custom_messages::Object_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sam_custom_messages::Object_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.id);
    s << indent << "type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.type);
    s << indent << "info[]" << std::endl;
    for (size_t i = 0; i < v.info.size(); ++i)
    {
      s << indent << "  info[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.info[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAM_CUSTOM_MESSAGES_MESSAGE_OBJECT_H
