// Generated by gencpp from file sam_custom_messages/diagnostics.msg
// DO NOT EDIT!


#ifndef SAM_CUSTOM_MESSAGES_MESSAGE_DIAGNOSTICS_H
#define SAM_CUSTOM_MESSAGES_MESSAGE_DIAGNOSTICS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <diagnostic_msgs/DiagnosticStatus.h>

namespace sam_custom_messages
{
template <class ContainerAllocator>
struct diagnostics_
{
  typedef diagnostics_<ContainerAllocator> Type;

  diagnostics_()
    : Header()
    , UserId(0)
    , UserName()
    , DiagnosticStatus()  {
    }
  diagnostics_(const ContainerAllocator& _alloc)
    : Header(_alloc)
    , UserId(0)
    , UserName(_alloc)
    , DiagnosticStatus(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _Header_type;
  _Header_type Header;

   typedef int8_t _UserId_type;
  _UserId_type UserId;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _UserName_type;
  _UserName_type UserName;

   typedef  ::diagnostic_msgs::DiagnosticStatus_<ContainerAllocator>  _DiagnosticStatus_type;
  _DiagnosticStatus_type DiagnosticStatus;





  typedef boost::shared_ptr< ::sam_custom_messages::diagnostics_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sam_custom_messages::diagnostics_<ContainerAllocator> const> ConstPtr;

}; // struct diagnostics_

typedef ::sam_custom_messages::diagnostics_<std::allocator<void> > diagnostics;

typedef boost::shared_ptr< ::sam_custom_messages::diagnostics > diagnosticsPtr;
typedef boost::shared_ptr< ::sam_custom_messages::diagnostics const> diagnosticsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sam_custom_messages::diagnostics_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sam_custom_messages::diagnostics_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sam_custom_messages::diagnostics_<ContainerAllocator1> & lhs, const ::sam_custom_messages::diagnostics_<ContainerAllocator2> & rhs)
{
  return lhs.Header == rhs.Header &&
    lhs.UserId == rhs.UserId &&
    lhs.UserName == rhs.UserName &&
    lhs.DiagnosticStatus == rhs.DiagnosticStatus;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sam_custom_messages::diagnostics_<ContainerAllocator1> & lhs, const ::sam_custom_messages::diagnostics_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sam_custom_messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sam_custom_messages::diagnostics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sam_custom_messages::diagnostics_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sam_custom_messages::diagnostics_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sam_custom_messages::diagnostics_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sam_custom_messages::diagnostics_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sam_custom_messages::diagnostics_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sam_custom_messages::diagnostics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d697c2568ce7a485465d81f6f70b8306";
  }

  static const char* value(const ::sam_custom_messages::diagnostics_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd697c2568ce7a485ULL;
  static const uint64_t static_value2 = 0x465d81f6f70b8306ULL;
};

template<class ContainerAllocator>
struct DataType< ::sam_custom_messages::diagnostics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sam_custom_messages/diagnostics";
  }

  static const char* value(const ::sam_custom_messages::diagnostics_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sam_custom_messages::diagnostics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "## Message containing diagnostic information for sensors/devices/users within the system\n"
"#\n"
"## std_msgs/Header.msg\n"
"# sequence ID: consecutively increasing ID \n"
"# uint32 seq\n"
"# Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"# time stamp\n"
"# Frame this data is associated with\n"
"# string frame_id\n"
"Header Header\n"
"#\n"
"## ID of user (robot or human)\n"
"int8 UserId\n"
"#\n"
"## Name of user (robot or human)\n"
"string UserName\n"
"#\n"
"## diagnostic_msgs/DiagnosticStatus.msg\n"
"# Possible levels of operations\n"
"# byte OK=0\n"
"# byte WARN=1\n"
"# byte ERROR=2\n"
"# byte STALE=3\n"
"# byte level # level of operation enumerated above \n"
"# string name # a description of the test/component reporting\n"
"# string message # a description of the status\n"
"# string hardware_id # a hardware unique string\n"
"# KeyValue[] values # an array of values associated with the status\n"
"diagnostic_msgs/DiagnosticStatus DiagnosticStatus\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: diagnostic_msgs/DiagnosticStatus\n"
"# This message holds the status of an individual component of the robot.\n"
"# \n"
"\n"
"# Possible levels of operations\n"
"byte OK=0\n"
"byte WARN=1\n"
"byte ERROR=2\n"
"byte STALE=3\n"
"\n"
"byte level # level of operation enumerated above \n"
"string name # a description of the test/component reporting\n"
"string message # a description of the status\n"
"string hardware_id # a hardware unique string\n"
"KeyValue[] values # an array of values associated with the status\n"
"\n"
"\n"
"================================================================================\n"
"MSG: diagnostic_msgs/KeyValue\n"
"string key # what to label this value when viewing\n"
"string value # a value to track over time\n"
;
  }

  static const char* value(const ::sam_custom_messages::diagnostics_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sam_custom_messages::diagnostics_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Header);
      stream.next(m.UserId);
      stream.next(m.UserName);
      stream.next(m.DiagnosticStatus);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct diagnostics_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sam_custom_messages::diagnostics_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sam_custom_messages::diagnostics_<ContainerAllocator>& v)
  {
    s << indent << "Header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.Header);
    s << indent << "UserId: ";
    Printer<int8_t>::stream(s, indent + "  ", v.UserId);
    s << indent << "UserName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.UserName);
    s << indent << "DiagnosticStatus: ";
    s << std::endl;
    Printer< ::diagnostic_msgs::DiagnosticStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.DiagnosticStatus);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAM_CUSTOM_MESSAGES_MESSAGE_DIAGNOSTICS_H
