// Generated by gencpp from file sam_custom_messages/hand_pos.msg
// DO NOT EDIT!


#ifndef SAM_CUSTOM_MESSAGES_MESSAGE_HAND_POS_H
#define SAM_CUSTOM_MESSAGES_MESSAGE_HAND_POS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace sam_custom_messages
{
template <class ContainerAllocator>
struct hand_pos_
{
  typedef hand_pos_<ContainerAllocator> Type;

  hand_pos_()
    : Header()
    , UserId(0)
    , UserName()
    , Hand(0)
    , Pose()  {
    }
  hand_pos_(const ContainerAllocator& _alloc)
    : Header(_alloc)
    , UserId(0)
    , UserName(_alloc)
    , Hand(0)
    , Pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _Header_type;
  _Header_type Header;

   typedef int8_t _UserId_type;
  _UserId_type UserId;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _UserName_type;
  _UserName_type UserName;

   typedef int8_t _Hand_type;
  _Hand_type Hand;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _Pose_type;
  _Pose_type Pose;





  typedef boost::shared_ptr< ::sam_custom_messages::hand_pos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sam_custom_messages::hand_pos_<ContainerAllocator> const> ConstPtr;

}; // struct hand_pos_

typedef ::sam_custom_messages::hand_pos_<std::allocator<void> > hand_pos;

typedef boost::shared_ptr< ::sam_custom_messages::hand_pos > hand_posPtr;
typedef boost::shared_ptr< ::sam_custom_messages::hand_pos const> hand_posConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sam_custom_messages::hand_pos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sam_custom_messages::hand_pos_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sam_custom_messages::hand_pos_<ContainerAllocator1> & lhs, const ::sam_custom_messages::hand_pos_<ContainerAllocator2> & rhs)
{
  return lhs.Header == rhs.Header &&
    lhs.UserId == rhs.UserId &&
    lhs.UserName == rhs.UserName &&
    lhs.Hand == rhs.Hand &&
    lhs.Pose == rhs.Pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sam_custom_messages::hand_pos_<ContainerAllocator1> & lhs, const ::sam_custom_messages::hand_pos_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sam_custom_messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sam_custom_messages::hand_pos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sam_custom_messages::hand_pos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sam_custom_messages::hand_pos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sam_custom_messages::hand_pos_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sam_custom_messages::hand_pos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sam_custom_messages::hand_pos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sam_custom_messages::hand_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3a4ac1d92f14f60ae68b389fe0ff85a";
  }

  static const char* value(const ::sam_custom_messages::hand_pos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3a4ac1d92f14f60ULL;
  static const uint64_t static_value2 = 0xae68b389fe0ff85aULL;
};

template<class ContainerAllocator>
struct DataType< ::sam_custom_messages::hand_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sam_custom_messages/hand_pos";
  }

  static const char* value(const ::sam_custom_messages::hand_pos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sam_custom_messages::hand_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "## Message containing location of a users hand\n"
"#\n"
"## std_msgs/Header.msg\n"
"# sequence ID: consecutively increasing ID \n"
"# uint32 seq\n"
"# Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"# time stamp\n"
"# Frame this data is associated with\n"
"# string frame_id\n"
"Header Header\n"
"#\n"
"## ID of user (robot or human)\n"
"int8 UserId\n"
"#\n"
"## Name of user (robot or human)\n"
"string UserName\n"
"#\n"
"## Which hand location is for, 0:left, 1:right\n"
"int8 Hand\n"
"#\n"
"# geometry_msgs/Pose.msg\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"# Point position\n"
"# Quaternion orientation\n"
"geometry_msgs/Pose Pose\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::sam_custom_messages::hand_pos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sam_custom_messages::hand_pos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Header);
      stream.next(m.UserId);
      stream.next(m.UserName);
      stream.next(m.Hand);
      stream.next(m.Pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hand_pos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sam_custom_messages::hand_pos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sam_custom_messages::hand_pos_<ContainerAllocator>& v)
  {
    s << indent << "Header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.Header);
    s << indent << "UserId: ";
    Printer<int8_t>::stream(s, indent + "  ", v.UserId);
    s << indent << "UserName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.UserName);
    s << indent << "Hand: ";
    Printer<int8_t>::stream(s, indent + "  ", v.Hand);
    s << indent << "Pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.Pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAM_CUSTOM_MESSAGES_MESSAGE_HAND_POS_H
