
classdef diagnostics < ros.Message
    %diagnostics MATLAB implementation of sam_custom_messages/diagnostics
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'sam_custom_messages/diagnostics' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '166ea485f1a6548735c38b7c8eac661c' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Diagnosticstatus' 'UserId' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'diagnosticstatus' 'user_id' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
			 'ros.msggen.diagnostic_msgs.DiagnosticStatus' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        Diagnosticstatus
        UserId
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'diagnostics', 'Header')
            obj.Header = val;
        end
        function set.Diagnosticstatus(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.diagnostic_msgs.DiagnosticStatus'};
            validateattributes(val, validClasses, validAttributes, 'diagnostics', 'Diagnosticstatus')
            obj.Diagnosticstatus = val;
        end
        function set.UserId(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'diagnostics', 'UserId');
            obj.UserId = int8(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.sam_custom_messages.diagnostics.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.sam_custom_messages.diagnostics;
            obj.reload(strObj);
        end
    end
end
