
classdef object_state < ros.Message
    %object_state MATLAB implementation of sam_custom_messages/object_state
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'sam_custom_messages/object_state' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '2219f508c564a641c1ef4997ea740e7e' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Object' 'Pose' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'object' 'pose' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
			 'ros.msggen.sam_custom_messages.Object' ...
			 'ros.msggen.geometry_msgs.Pose' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        Object
        Pose
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'object_state', 'Header')
            obj.Header = val;
        end
        function set.Object(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.sam_custom_messages.Object'};
            validateattributes(val, validClasses, validAttributes, 'object_state', 'Object')
            obj.Object = val;
        end
        function set.Pose(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Pose'};
            validateattributes(val, validClasses, validAttributes, 'object_state', 'Pose')
            obj.Pose = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.sam_custom_messages.object_state.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.sam_custom_messages.object_state;
            obj.reload(strObj);
        end
    end
end
