// Generated by gencpp from file sam_custom_messages/current_action.msg
// DO NOT EDIT!


#ifndef SAM_CUSTOM_MESSAGES_MESSAGE_CURRENT_ACTION_H
#define SAM_CUSTOM_MESSAGES_MESSAGE_CURRENT_ACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sam_custom_messages
{
template <class ContainerAllocator>
struct current_action_
{
  typedef current_action_<ContainerAllocator> Type;

  current_action_()
    : header()
    , user_id(0)
    , action_probs()  {
    }
  current_action_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , user_id(0)
    , action_probs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _user_id_type;
  _user_id_type user_id;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _action_probs_type;
  _action_probs_type action_probs;





  typedef boost::shared_ptr< ::sam_custom_messages::current_action_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sam_custom_messages::current_action_<ContainerAllocator> const> ConstPtr;

}; // struct current_action_

typedef ::sam_custom_messages::current_action_<std::allocator<void> > current_action;

typedef boost::shared_ptr< ::sam_custom_messages::current_action > current_actionPtr;
typedef boost::shared_ptr< ::sam_custom_messages::current_action const> current_actionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sam_custom_messages::current_action_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sam_custom_messages::current_action_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sam_custom_messages::current_action_<ContainerAllocator1> & lhs, const ::sam_custom_messages::current_action_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.user_id == rhs.user_id &&
    lhs.action_probs == rhs.action_probs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sam_custom_messages::current_action_<ContainerAllocator1> & lhs, const ::sam_custom_messages::current_action_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sam_custom_messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sam_custom_messages::current_action_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sam_custom_messages::current_action_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sam_custom_messages::current_action_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sam_custom_messages::current_action_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sam_custom_messages::current_action_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sam_custom_messages::current_action_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sam_custom_messages::current_action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "799d6ed84a84e9c791e69aeaf9e13c8a";
  }

  static const char* value(const ::sam_custom_messages::current_action_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x799d6ed84a84e9c7ULL;
  static const uint64_t static_value2 = 0x91e69aeaf9e13c8aULL;
};

template<class ContainerAllocator>
struct DataType< ::sam_custom_messages::current_action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sam_custom_messages/current_action";
  }

  static const char* value(const ::sam_custom_messages::current_action_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sam_custom_messages::current_action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "## Message containing predictions of what action user is currently performing\n"
"#\n"
"## std_msgs/Header.msg\n"
"# sequence ID: consecutively increasing ID \n"
"# uint32 seq\n"
"# Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"# time stamp\n"
"# Frame this data is associated with\n"
"# string frame_id\n"
"Header header\n"
"#\n"
"## ID of user (robot or human)\n"
"int8 user_id\n"
"#\n"
"## Probabilities of curent actions\n"
"float64[] action_probs\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sam_custom_messages::current_action_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sam_custom_messages::current_action_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.user_id);
      stream.next(m.action_probs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct current_action_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sam_custom_messages::current_action_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sam_custom_messages::current_action_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "user_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.user_id);
    s << indent << "action_probs[]" << std::endl;
    for (size_t i = 0; i < v.action_probs.size(); ++i)
    {
      s << indent << "  action_probs[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.action_probs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAM_CUSTOM_MESSAGES_MESSAGE_CURRENT_ACTION_H
