// Generated by gencpp from file sam_custom_messages/Object.msg
// DO NOT EDIT!


#ifndef SAM_CUSTOM_MESSAGES_MESSAGE_OBJECT_H
#define SAM_CUSTOM_MESSAGES_MESSAGE_OBJECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sam_custom_messages
{
template <class ContainerAllocator>
struct Object_
{
  typedef Object_<ContainerAllocator> Type;

  Object_()
    : id(0)
    , type(0)
    , info()  {
    }
  Object_(const ContainerAllocator& _alloc)
    : id(0)
    , type(0)
    , info(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _id_type;
  _id_type id;

   typedef int8_t _type_type;
  _type_type type;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _info_type;
  _info_type info;





  typedef boost::shared_ptr< ::sam_custom_messages::Object_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sam_custom_messages::Object_<ContainerAllocator> const> ConstPtr;

}; // struct Object_

typedef ::sam_custom_messages::Object_<std::allocator<void> > Object;

typedef boost::shared_ptr< ::sam_custom_messages::Object > ObjectPtr;
typedef boost::shared_ptr< ::sam_custom_messages::Object const> ObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sam_custom_messages::Object_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sam_custom_messages::Object_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sam_custom_messages::Object_<ContainerAllocator1> & lhs, const ::sam_custom_messages::Object_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.type == rhs.type &&
    lhs.info == rhs.info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sam_custom_messages::Object_<ContainerAllocator1> & lhs, const ::sam_custom_messages::Object_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sam_custom_messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sam_custom_messages::Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sam_custom_messages::Object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sam_custom_messages::Object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sam_custom_messages::Object_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sam_custom_messages::Object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sam_custom_messages::Object_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sam_custom_messages::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc95ebc586991f7be21fb0175298a82c";
  }

  static const char* value(const ::sam_custom_messages::Object_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc95ebc586991f7bULL;
  static const uint64_t static_value2 = 0xe21fb0175298a82cULL;
};

template<class ContainerAllocator>
struct DataType< ::sam_custom_messages::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sam_custom_messages/Object";
  }

  static const char* value(const ::sam_custom_messages::Object_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sam_custom_messages::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message containg information on objects within environment\n"
"#\n"
"# Unique ID of object\n"
"int8 id\n"
"#\n"
"# Type of object ID\n"
"int8 type\n"
"#\n"
"# Additional information on object\n"
"string[] info\n"
;
  }

  static const char* value(const ::sam_custom_messages::Object_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sam_custom_messages::Object_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.type);
      stream.next(m.info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Object_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sam_custom_messages::Object_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sam_custom_messages::Object_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.id);
    s << indent << "type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.type);
    s << indent << "info[]" << std::endl;
    for (size_t i = 0; i < v.info.size(); ++i)
    {
      s << indent << "  info[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.info[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAM_CUSTOM_MESSAGES_MESSAGE_OBJECT_H
