// Generated by gencpp from file sam_custom_messages/diagnostics.msg
// DO NOT EDIT!


#ifndef SAM_CUSTOM_MESSAGES_MESSAGE_DIAGNOSTICS_H
#define SAM_CUSTOM_MESSAGES_MESSAGE_DIAGNOSTICS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <diagnostic_msgs/DiagnosticStatus.h>

namespace sam_custom_messages
{
template <class ContainerAllocator>
struct diagnostics_
{
  typedef diagnostics_<ContainerAllocator> Type;

  diagnostics_()
    : header()
    , user_id(0)
    , diagnosticstatus()  {
    }
  diagnostics_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , user_id(0)
    , diagnosticstatus(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _user_id_type;
  _user_id_type user_id;

   typedef  ::diagnostic_msgs::DiagnosticStatus_<ContainerAllocator>  _diagnosticstatus_type;
  _diagnosticstatus_type diagnosticstatus;





  typedef boost::shared_ptr< ::sam_custom_messages::diagnostics_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sam_custom_messages::diagnostics_<ContainerAllocator> const> ConstPtr;

}; // struct diagnostics_

typedef ::sam_custom_messages::diagnostics_<std::allocator<void> > diagnostics;

typedef boost::shared_ptr< ::sam_custom_messages::diagnostics > diagnosticsPtr;
typedef boost::shared_ptr< ::sam_custom_messages::diagnostics const> diagnosticsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sam_custom_messages::diagnostics_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sam_custom_messages::diagnostics_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sam_custom_messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['C:/Program Files/MATLAB/R2020b/sys/ros1/win64/ros1/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['C:/Program Files/MATLAB/R2020b/sys/ros1/win64/ros1/share/geometry_msgs/cmake/../msg'], 'sam_custom_messages': ['C:/Users/inter/Documents/NatNet_SDK_3.1/NatNetSDK/Industrial_SAM/matlab_msg_gen_ros1/win64/src/sam_custom_messages/msg'], 'std_msgs': ['C:/Program Files/MATLAB/R2020b/sys/ros1/win64/ros1/share/std_msgs/cmake/../msg', 'C:/Program Files/MATLAB/R2020b/sys/ros1/win64/ros1/share/std_msgs/cmake/../msg'], 'diagnostic_msgs': ['C:/Program Files/MATLAB/R2020b/sys/ros1/win64/ros1/share/diagnostic_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sam_custom_messages::diagnostics_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sam_custom_messages::diagnostics_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sam_custom_messages::diagnostics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sam_custom_messages::diagnostics_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sam_custom_messages::diagnostics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sam_custom_messages::diagnostics_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sam_custom_messages::diagnostics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "166ea485f1a6548735c38b7c8eac661c";
  }

  static const char* value(const ::sam_custom_messages::diagnostics_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x166ea485f1a65487ULL;
  static const uint64_t static_value2 = 0x35c38b7c8eac661cULL;
};

template<class ContainerAllocator>
struct DataType< ::sam_custom_messages::diagnostics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sam_custom_messages/diagnostics";
  }

  static const char* value(const ::sam_custom_messages::diagnostics_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sam_custom_messages::diagnostics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "## Message containing diagnostic information for sensors/devices/users within the system\n"
"#\n"
"## std_msgs/Header.msg\n"
"# sequence ID: consecutively increasing ID \n"
"# uint32 seq\n"
"# Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"# time stamp\n"
"# Frame this data is associated with\n"
"# string frame_id\n"
"Header header\n"
"#\n"
"## ID of user (robot or human)\n"
"int8 user_id\n"
"#\n"
"## diagnostic_msgs/DiagnosticStatus.msg\n"
"# Possible levels of operations\n"
"# byte OK=0\n"
"# byte WARN=1\n"
"# byte ERROR=2\n"
"# byte STALE=3\n"
"# byte level # level of operation enumerated above \n"
"# string name # a description of the test/component reporting\n"
"# string message # a description of the status\n"
"# string hardware_id # a hardware unique string\n"
"# KeyValue[] values # an array of values associated with the status\n"
"diagnostic_msgs/DiagnosticStatus diagnosticstatus\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: diagnostic_msgs/DiagnosticStatus\n"
"# This message holds the status of an individual component of the robot.\n"
"# \n"
"\n"
"# Possible levels of operations\n"
"byte OK=0\n"
"byte WARN=1\n"
"byte ERROR=2\n"
"byte STALE=3\n"
"\n"
"byte level # level of operation enumerated above \n"
"string name # a description of the test/component reporting\n"
"string message # a description of the status\n"
"string hardware_id # a hardware unique string\n"
"KeyValue[] values # an array of values associated with the status\n"
"\n"
"\n"
"================================================================================\n"
"MSG: diagnostic_msgs/KeyValue\n"
"string key # what to label this value when viewing\n"
"string value # a value to track over time\n"
;
  }

  static const char* value(const ::sam_custom_messages::diagnostics_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sam_custom_messages::diagnostics_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.user_id);
      stream.next(m.diagnosticstatus);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct diagnostics_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sam_custom_messages::diagnostics_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sam_custom_messages::diagnostics_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "user_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.user_id);
    s << indent << "diagnosticstatus: ";
    s << std::endl;
    Printer< ::diagnostic_msgs::DiagnosticStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.diagnosticstatus);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAM_CUSTOM_MESSAGES_MESSAGE_DIAGNOSTICS_H
